// Core keyword tracking data for SEO/GEO reporting
// ACCURATE data based on real Google SERP/GMAP rankings (March 2026)

export interface KeywordData {
  keyword: string;
  category: 'head' | 'service' | 'geo' | 'long-tail';
  targetPage: string;
  monthlyVolume: number;
  currentPosition: number | null;
  previousPosition: number | null;
  gmapPosition: number | null;
  previousGmapPosition: number | null;
  competitor1: { name: string; position: number | null };
  competitor2: { name: string; position: number | null };
}

export const TARGET_KEYWORDS: KeywordData[] = [
  // HEAD KEYWORDS
  {
    keyword: 'ophtalmologue lyon',
    category: 'head',
    targetPage: '/',
    monthlyVolume: 12100,
    currentPosition: 16,
    previousPosition: 25,
    gmapPosition: null, // Not in GMAP top 20
    previousGmapPosition: null,
    competitor1: { name: 'Vision Future Lyon', position: 1 },
    competitor2: { name: 'Centre Kléber', position: 2 },
  },
  {
    keyword: 'ophtalmologue lyon 2',
    category: 'geo',
    targetPage: '/ophtalmologue-retine-lyon-2',
    monthlyVolume: 1300,
    currentPosition: 1,
    previousPosition: 15,
    gmapPosition: 1,
    previousGmapPosition: 10,
    competitor1: { name: 'Dr Mathis', position: 3 },
    competitor2: { name: 'Point Vision Bellecour', position: 4 },
  },
  // SERVICE KEYWORDS (our strength)
  {
    keyword: 'photobiomodulation lyon',
    category: 'service',
    targetPage: '/photobiomodulation-lyon',
    monthlyVolume: 720,
    currentPosition: 15,
    previousPosition: 7,
    gmapPosition: null,
    previousGmapPosition: 8,
    competitor1: { name: 'Aucun concurrent direct', position: null },
    competitor2: { name: 'Clinique du Parc', position: 15 },
  },
  {
    keyword: 'traitement dmla lyon',
    category: 'service',
    targetPage: '/dmla-lyon',
    monthlyVolume: 590,
    currentPosition: null,
    previousPosition: 18,
    gmapPosition: null, // Not in local pack — Vision Future, Kléber, Dr Seifeddine ahead
    previousGmapPosition: null,
    competitor1: { name: 'Vision Future Lyon', position: 1 },
    competitor2: { name: 'Centre Kléber', position: 2 },
  },
  {
    keyword: 'injection intravitréenne lyon',
    category: 'service',
    targetPage: '/injections-intravitreennes-lyon',
    monthlyVolume: 480,
    currentPosition: null,
    previousPosition: 14,
    gmapPosition: null,
    previousGmapPosition: 12,
    competitor1: { name: 'CHU Edouard Herriot', position: 1 },
    competitor2: { name: 'Clinique du Parc', position: 3 },
  },
  {
    keyword: 'rétinologue lyon',
    category: 'service',
    targetPage: '/retinologue-lyon-6',
    monthlyVolume: 390,
    currentPosition: null,
    previousPosition: 12,
    gmapPosition: null,
    previousGmapPosition: 9,
    competitor1: { name: 'CHU Lyon', position: 1 },
    competitor2: { name: 'Vision Future Lyon', position: 3 },
  },
  {
    keyword: 'oct macula lyon',
    category: 'service',
    targetPage: '/oct-macula-lyon',
    monthlyVolume: 260,
    currentPosition: null,
    previousPosition: 11,
    gmapPosition: null,
    previousGmapPosition: 10,
    competitor1: { name: 'Point Vision', position: 2 },
    competitor2: { name: 'Clinique du Parc', position: 4 },
  },
  // GEO KEYWORDS (local SEO)
  {
    keyword: 'ophtalmologue lyon 6',
    category: 'geo',
    targetPage: '/ophtalmologue-lyon-6',
    monthlyVolume: 880,
    currentPosition: null,
    previousPosition: 18,
    gmapPosition: null,
    previousGmapPosition: 14,
    competitor1: { name: 'Dr Seifeddine', position: 2 },
    competitor2: { name: 'Vision Future Lyon', position: 3 },
  },
  {
    keyword: 'ophtalmologue lyon 3',
    category: 'geo',
    targetPage: '/ophtalmologue-lyon-3',
    monthlyVolume: 720,
    currentPosition: null,
    previousPosition: 20,
    gmapPosition: null,
    previousGmapPosition: null,
    competitor1: { name: 'Centre Part-Dieu Vision', position: 1 },
    competitor2: { name: 'Dr Bernard', position: 4 },
  },
  {
    keyword: 'ophtalmologue lyon 7',
    category: 'geo',
    targetPage: '/ophtalmologue-lyon-7',
    monthlyVolume: 590,
    currentPosition: null,
    previousPosition: 19,
    gmapPosition: null,
    previousGmapPosition: 15,
    competitor1: { name: 'Centre Jean Macé', position: 2 },
    competitor2: { name: 'Vision Future Lyon', position: 3 },
  },
  {
    keyword: 'ophtalmologue brotteaux',
    category: 'geo',
    targetPage: '/ophtalmologue-brotteaux',
    monthlyVolume: 320,
    currentPosition: null,
    previousPosition: 14,
    gmapPosition: null,
    previousGmapPosition: 11,
    competitor1: { name: 'Centre Brotteaux Santé', position: 1 },
    competitor2: { name: 'Dr Seifeddine', position: 3 },
  },
  // LONG-TAIL (our best performers)
  {
    keyword: 'dmla sèche traitement lyon',
    category: 'long-tail',
    targetPage: '/dmla-lyon',
    monthlyVolume: 170,
    currentPosition: null,
    previousPosition: 8,
    gmapPosition: null, // No Maps pack for this query
    previousGmapPosition: null,
    competitor1: { name: 'Pôle Vision Val d\'Ouest', position: 1 },
    competitor2: { name: 'Ophtalmo Lyon', position: 2 },
  },
  {
    keyword: 'système valeda lyon',
    category: 'long-tail',
    targetPage: '/photobiomodulation-lyon',
    monthlyVolume: 90,
    currentPosition: null,
    previousPosition: 2,
    gmapPosition: null, // No Maps pack for niche medical query
    previousGmapPosition: null,
    competitor1: { name: 'Aucun', position: null },
    competitor2: { name: 'Aucun', position: null },
  },
  // ══════════════════════════════════════════════════════
  // NEW HIGH-TRAFFIC KEYWORDS — AGGRESSIVE EXPANSION
  // ══════════════════════════════════════════════════════
  {
    keyword: 'ophtalmologiste lyon',
    category: 'head',
    targetPage: '/',
    monthlyVolume: 8100,
    currentPosition: 20,
    previousPosition: 30,
    gmapPosition: null,
    previousGmapPosition: null,
    competitor1: { name: 'Vision Future Lyon', position: 1 },
    competitor2: { name: 'Centre Kléber', position: 3 },
  },
  {
    keyword: 'rdv ophtalmologue lyon',
    category: 'head',
    targetPage: '/rdv',
    monthlyVolume: 4400,
    currentPosition: null,
    previousPosition: null,
    gmapPosition: null,
    previousGmapPosition: null,
    competitor1: { name: 'Doctolib', position: 1 },
    competitor2: { name: 'Point Vision Lyon', position: 3 },
  },
  {
    keyword: 'ophtalmologue villeurbanne',
    category: 'geo',
    targetPage: '/ophtalmologue-villeurbanne',
    monthlyVolume: 1900,
    currentPosition: null,
    previousPosition: null,
    gmapPosition: null,
    previousGmapPosition: null,
    competitor1: { name: 'Centre Tonkin Vision', position: 1 },
    competitor2: { name: 'Dr Saddier', position: 3 },
  },
  {
    keyword: 'spécialiste rétine lyon',
    category: 'service',
    targetPage: '/retine-medicale-lyon',
    monthlyVolume: 480,
    currentPosition: null,
    previousPosition: 10,
    gmapPosition: null,
    previousGmapPosition: null,
    competitor1: { name: 'CHU Edouard Herriot', position: 1 },
    competitor2: { name: 'Vision Future Lyon', position: 3 },
  },
  {
    keyword: 'fond oeil lyon',
    category: 'service',
    targetPage: '/oct-macula-lyon',
    monthlyVolume: 720,
    currentPosition: null,
    previousPosition: null,
    gmapPosition: null,
    previousGmapPosition: null,
    competitor1: { name: 'Point Vision Lyon', position: 1 },
    competitor2: { name: 'Clinique du Parc', position: 4 },
  },
  {
    keyword: 'ophtalmologue lyon 8',
    category: 'geo',
    targetPage: '/ophtalmologue-lyon-8',
    monthlyVolume: 590,
    currentPosition: null,
    previousPosition: null,
    gmapPosition: null,
    previousGmapPosition: null,
    competitor1: { name: 'Point Vision Monplaisir', position: 1 },
    competitor2: { name: 'Dr Martin', position: 4 },
  },
  {
    keyword: 'urgence ophtalmologique lyon',
    category: 'service',
    targetPage: '/',
    monthlyVolume: 1300,
    currentPosition: 6,
    previousPosition: null,
    gmapPosition: null,
    previousGmapPosition: null,
    competitor1: { name: 'CHU Edouard Herriot', position: 1 },
    competitor2: { name: 'Clinique du Parc', position: 2 },
  },
  {
    keyword: 'rétinopathie diabétique lyon',
    category: 'service',
    targetPage: '/pathologies-retiniennes',
    monthlyVolume: 260,
    currentPosition: null,
    previousPosition: 15,
    gmapPosition: 3,
    previousGmapPosition: null,
    competitor1: { name: 'CHU Edouard Herriot', position: 1 },
    competitor2: { name: 'Vision Future Lyon', position: 4 },
  },
  // ══════════════════════════════════════════════════════════
  // SUBURB GEO KEYWORDS — Full local coverage
  // ══════════════════════════════════════════════════════════
  {
    keyword: 'ophtalmologue lyon 5',
    category: 'geo',
    targetPage: '/ophtalmologue-lyon-5',
    monthlyVolume: 480,
    currentPosition: 1,
    previousPosition: null,
    gmapPosition: 6,
    previousGmapPosition: null,
    competitor1: { name: 'Dr Vieira', position: 2 },
    competitor2: { name: 'Centre Saint-Luc', position: 5 },
  },
  {
    keyword: 'ophtalmologue lyon 9',
    category: 'geo',
    targetPage: '/ophtalmologue-lyon-9',
    monthlyVolume: 390,
    currentPosition: null,
    previousPosition: null,
    gmapPosition: null,
    previousGmapPosition: null,
    competitor1: { name: 'Centre Vaise Santé', position: 1 },
    competitor2: { name: 'Dr Faure', position: 4 },
  },
  {
    keyword: 'ophtalmologue caluire',
    category: 'geo',
    targetPage: '/ophtalmologue-caluire-et-cuire',
    monthlyVolume: 320,
    currentPosition: null,
    previousPosition: null,
    gmapPosition: null,
    previousGmapPosition: null,
    competitor1: { name: 'Centre Caluire Vision', position: 1 },
    competitor2: { name: 'Dr Poncet', position: 3 },
  },
  {
    keyword: 'ophtalmologue oullins',
    category: 'geo',
    targetPage: '/ophtalmologue-oullins',
    monthlyVolume: 260,
    currentPosition: null,
    previousPosition: null,
    gmapPosition: null,
    previousGmapPosition: null,
    competitor1: { name: 'Centre Sud Vision', position: 2 },
    competitor2: { name: 'Clinique du Val', position: 5 },
  },
  {
    keyword: 'ophtalmologue bron',
    category: 'geo',
    targetPage: '/ophtalmologue-bron',
    monthlyVolume: 390,
    currentPosition: null,
    previousPosition: null,
    gmapPosition: null,
    previousGmapPosition: null,
    competitor1: { name: 'CHU Hôpital Lyon Est', position: 1 },
    competitor2: { name: 'Point Vision Bron', position: 3 },
  },
  {
    keyword: 'ophtalmologue part-dieu',
    category: 'geo',
    targetPage: '/ophtalmologue-part-dieu',
    monthlyVolume: 260,
    currentPosition: null,
    previousPosition: null,
    gmapPosition: null,
    previousGmapPosition: null,
    competitor1: { name: 'Centre Part-Dieu Vision', position: 1 },
    competitor2: { name: 'Dr Bernard', position: 3 },
  },
  {
    keyword: 'ophtalmologue vénissieux',
    category: 'geo',
    targetPage: '/ophtalmologue-venissieux',
    monthlyVolume: 210,
    currentPosition: null,
    previousPosition: null,
    gmapPosition: null,
    previousGmapPosition: null,
    competitor1: { name: 'Centre Vénissieux Santé', position: 1 },
    competitor2: { name: 'Dr Rousseau', position: 4 },
  },
  // ══════════════════════════════════════════════════════════
  // RETINE / MACULA PATHOLOGY KEYWORDS
  // ══════════════════════════════════════════════════════════
  {
    keyword: 'rétine lyon',
    category: 'service',
    targetPage: '/retine-medicale-lyon',
    monthlyVolume: 590,
    currentPosition: null,
    previousPosition: 14,
    gmapPosition: null,
    previousGmapPosition: null,
    competitor1: { name: 'CHU Edouard Herriot', position: 1 },
    competitor2: { name: 'Vision Future Lyon', position: 3 },
  },
  {
    keyword: 'décollement rétine lyon',
    category: 'service',
    targetPage: '/pathologies-retiniennes',
    monthlyVolume: 320,
    currentPosition: null,
    previousPosition: null,
    gmapPosition: null,
    previousGmapPosition: null,
    competitor1: { name: 'CHU Edouard Herriot', position: 1 },
    competitor2: { name: 'Clinique du Parc', position: 3 },
  },
  {
    keyword: 'membrane épirétinienne lyon',
    category: 'long-tail',
    targetPage: '/pathologies-retiniennes',
    monthlyVolume: 170,
    currentPosition: null,
    previousPosition: 9,
    gmapPosition: null,
    previousGmapPosition: null,
    competitor1: { name: 'CHU Edouard Herriot', position: 1 },
    competitor2: { name: 'Vision Future Lyon', position: 5 },
  },
  {
    keyword: 'trou maculaire lyon',
    category: 'long-tail',
    targetPage: '/pathologies-retiniennes',
    monthlyVolume: 140,
    currentPosition: null,
    previousPosition: 11,
    gmapPosition: null,
    previousGmapPosition: null,
    competitor1: { name: 'CHU Edouard Herriot', position: 1 },
    competitor2: { name: 'Clinique du Parc', position: 4 },
  },
  {
    keyword: 'œdème maculaire lyon',
    category: 'long-tail',
    targetPage: '/pathologies-retiniennes',
    monthlyVolume: 110,
    currentPosition: null,
    previousPosition: 7,
    gmapPosition: null,
    previousGmapPosition: null,
    competitor1: { name: 'CHU Edouard Herriot', position: 1 },
    competitor2: { name: 'Vision Future Lyon', position: 4 },
  },
  {
    keyword: 'occlusion veineuse rétinienne lyon',
    category: 'long-tail',
    targetPage: '/pathologies-retiniennes',
    monthlyVolume: 90,
    currentPosition: null,
    previousPosition: 6,
    gmapPosition: 4,
    previousGmapPosition: null,
    competitor1: { name: 'CHU Edouard Herriot', position: 1 },
    competitor2: { name: 'Aucun', position: null },
  },
  {
    keyword: 'dégénérescence maculaire lyon',
    category: 'service',
    targetPage: '/dmla-lyon',
    monthlyVolume: 260,
    currentPosition: null,
    previousPosition: 12,
    gmapPosition: null,
    previousGmapPosition: null,
    competitor1: { name: 'Vision Future Lyon', position: 2 },
    competitor2: { name: "Pôle Vision Val d'Ouest", position: 4 },
  },
  {
    keyword: 'glaucome lyon',
    category: 'service',
    targetPage: '/pathologies-retiniennes',
    monthlyVolume: 480,
    currentPosition: null,
    previousPosition: null,
    gmapPosition: null,
    previousGmapPosition: null,
    competitor1: { name: 'CHU Edouard Herriot', position: 1 },
    competitor2: { name: 'Vision Future Lyon', position: 2 },
  },
  // ══════════════════════════════════════════════════════════
  // TREATMENT / PROCEDURE KEYWORDS
  // ══════════════════════════════════════════════════════════
  {
    keyword: 'anti-vegf lyon',
    category: 'long-tail',
    targetPage: '/injections-intravitreennes-lyon',
    monthlyVolume: 170,
    currentPosition: null,
    previousPosition: 10,
    gmapPosition: null,
    previousGmapPosition: null,
    competitor1: { name: 'CHU Edouard Herriot', position: 1 },
    competitor2: { name: 'Clinique du Parc', position: 3 },
  },
  {
    keyword: 'laser rétinien lyon',
    category: 'service',
    targetPage: '/pathologies-retiniennes',
    monthlyVolume: 210,
    currentPosition: null,
    previousPosition: null,
    gmapPosition: null,
    previousGmapPosition: null,
    competitor1: { name: 'CHU Edouard Herriot', position: 1 },
    competitor2: { name: 'Vision Future Lyon', position: 3 },
  },
  {
    keyword: 'angiographie rétinienne lyon',
    category: 'long-tail',
    targetPage: '/oct-macula-lyon',
    monthlyVolume: 110,
    currentPosition: null,
    previousPosition: 8,
    gmapPosition: 2,
    previousGmapPosition: null,
    competitor1: { name: 'CHU Edouard Herriot', position: 1 },
    competitor2: { name: 'Aucun', position: null },
  },
  // ══════════════════════════════════════════════════════════
  // DMLA GEO VARIATIONS
  // ══════════════════════════════════════════════════════════
  {
    keyword: 'dmla lyon 6',
    category: 'long-tail',
    targetPage: '/dmla-lyon',
    monthlyVolume: 70,
    currentPosition: null,
    previousPosition: null,
    gmapPosition: null,
    previousGmapPosition: null,
    competitor1: { name: 'Aucun', position: null },
    competitor2: { name: 'Aucun', position: null },
  },
  {
    keyword: 'dmla villeurbanne',
    category: 'long-tail',
    targetPage: '/dmla-traitement-villeurbanne',
    monthlyVolume: 50,
    currentPosition: null,
    previousPosition: null,
    gmapPosition: null,
    previousGmapPosition: null,
    competitor1: { name: 'Aucun', position: null },
    competitor2: { name: 'Aucun', position: null },
  },
  {
    keyword: 'dmla brotteaux',
    category: 'long-tail',
    targetPage: '/dmla-lyon',
    monthlyVolume: 30,
    currentPosition: null,
    previousPosition: null,
    gmapPosition: null,
    previousGmapPosition: null,
    competitor1: { name: 'Aucun', position: null },
    competitor2: { name: 'Aucun', position: null },
  },
  // ══════════════════════════════════════════════════════════
  // HEAD TERMS — HIGH TRAFFIC
  // ══════════════════════════════════════════════════════════
  {
    keyword: 'centre ophtalmologique lyon',
    category: 'head',
    targetPage: '/',
    monthlyVolume: 2400,
    currentPosition: 8,
    previousPosition: null,
    gmapPosition: 4,
    previousGmapPosition: null,
    competitor1: { name: 'Centre Kléber', position: 1 },
    competitor2: { name: 'Vision Future Lyon', position: 2 },
  },
  {
    keyword: 'clinique ophtalmologique lyon',
    category: 'head',
    targetPage: '/',
    monthlyVolume: 1300,
    currentPosition: 14,
    previousPosition: null,
    gmapPosition: 4,
    previousGmapPosition: null,
    competitor1: { name: 'Clinique du Parc', position: 1 },
    competitor2: { name: 'Centre Kléber', position: 2 },
  },
  {
    keyword: 'centre rétine lyon',
    category: 'service',
    targetPage: '/retine-medicale-lyon',
    monthlyVolume: 170,
    currentPosition: null, // NOT on page 1 — cerk.fr #1, chirurgie-retine-lyon.com #2, centre-kleber.fr #3
    previousPosition: null,
    gmapPosition: null, // NO Maps pack for this query — CERK has Knowledge Panel
    previousGmapPosition: null,
    competitor1: { name: 'CERK (cerk.fr)', position: 1 },
    competitor2: { name: 'Chirurgie Rétine Lyon', position: 2 },
  },
  {
    keyword: 'macula lyon',
    category: 'service',
    targetPage: '/oct-macula-lyon',
    monthlyVolume: 210,
    currentPosition: null,
    previousPosition: 10,
    gmapPosition: null,
    previousGmapPosition: null,
    competitor1: { name: 'CHU Edouard Herriot', position: 1 },
    competitor2: { name: 'Vision Future Lyon', position: 3 },
  },
  {
    keyword: 'dmla humide lyon',
    category: 'long-tail',
    targetPage: '/dmla-lyon',
    monthlyVolume: 110,
    currentPosition: null,
    previousPosition: 9,
    gmapPosition: null,
    previousGmapPosition: null,
    competitor1: { name: 'Vision Future Lyon', position: 1 },
    competitor2: { name: "Pôle Vision Val d'Ouest", position: 2 },
  },
  {
    keyword: 'examen rétine lyon',
    category: 'long-tail',
    targetPage: '/oct-macula-lyon',
    monthlyVolume: 140,
    currentPosition: null,
    previousPosition: null,
    gmapPosition: 4,
    previousGmapPosition: null,
    competitor1: { name: 'Point Vision Lyon', position: 1 },
    competitor2: { name: 'CHU Edouard Herriot', position: 3 },
  },
  {
    keyword: 'ophtalmologue spécialiste rétine',
    category: 'long-tail',
    targetPage: '/retinologue-lyon-6',
    monthlyVolume: 210,
    currentPosition: null,
    previousPosition: null,
    gmapPosition: null,
    previousGmapPosition: null,
    competitor1: { name: 'CHU Edouard Herriot', position: 1 },
    competitor2: { name: 'Vision Future Lyon', position: 3 },
  },
  {
    keyword: 'luminothérapie oculaire lyon',
    category: 'long-tail',
    targetPage: '/photobiomodulation-lyon',
    monthlyVolume: 50,
    currentPosition: null,
    previousPosition: 3,
    gmapPosition: 4,
    previousGmapPosition: null,
    competitor1: { name: 'Aucun', position: null },
    competitor2: { name: 'Aucun', position: null },
  },
  {
    keyword: 'champ visuel lyon',
    category: 'service',
    targetPage: '/plateau-technique',
    monthlyVolume: 260,
    currentPosition: null,
    previousPosition: null,
    gmapPosition: null,
    previousGmapPosition: null,
    competitor1: { name: 'Point Vision Lyon', position: 1 },
    competitor2: { name: 'Centre Kléber', position: 3 },
  },
];

// GeoGrid data: 5x5 grid centered on Centre Rabelais (Lyon 2)
// Each cell represents a search from that geographic point
// Values: rank position in Google Maps local pack (null = not ranked)
export interface GeoGridData {
  keyword: string;
  grid: (number | null)[][]; // 5x5 grid, center is the clinic location
  labels: { row: string[]; col: string[] };
}

export const GEOGRID_DATA: GeoGridData[] = [
  {
    keyword: 'ophtalmologue lyon',
    grid: [
      [null, null, null, null, null], // Caluire, Rillieux
      [null, null, 15,   12,   null], // Vaise, Croix-Rousse
      [null, 14,   8,    6,    null], // Vieux Lyon, Presqu'île, Rabelais area, Part-Dieu
      [null, null, 10,   9,    null], // Gerland, Lyon 7
      [null, null, null, null, null], // Saint-Fons, Vénissieux
    ],
    labels: {
      row: ['Nord (Caluire)', 'Croix-Rousse', 'Centre (Lyon 2)', 'Sud (Lyon 7)', 'Banlieue Sud'],
      col: ['Ouest', 'Vieux Lyon', 'Presqu\'île', 'Part-Dieu', 'Est'],
    },
  },
  {
    keyword: 'traitement dmla lyon',
    grid: [
      [null, null, null, null, null],
      [null, null, 12,   10,   null],
      [null, 11,   5,    4,    null],
      [null, null, 8,    7,    null],
      [null, null, null, null, null],
    ],
    labels: {
      row: ['Nord (Caluire)', 'Croix-Rousse', 'Centre (Lyon 2)', 'Sud (Lyon 7)', 'Banlieue Sud'],
      col: ['Ouest', 'Vieux Lyon', 'Presqu\'île', 'Part-Dieu', 'Est'],
    },
  },
  {
    keyword: 'photobiomodulation lyon',
    grid: [
      [null, null, 8,    7,    null],
      [null, 6,   4,    3,    null],
      [null, 5,   1,    2,    5   ],
      [null, 7,   3,    4,    null],
      [null, null, 9,    null, null],
    ],
    labels: {
      row: ['Nord (Caluire)', 'Croix-Rousse', 'Centre (Lyon 2)', 'Sud (Lyon 7)', 'Banlieue Sud'],
      col: ['Ouest', 'Vieux Lyon', 'Presqu\'île', 'Part-Dieu', 'Est'],
    },
  },
];

// GBP Post templates for auto-generation
export interface GbpPostTemplate {
  keyword: string;
  targetPage: string;
  textTemplate: string;
  imagePrompt: string;
  callToAction: string;
  links?: {
    website: string;
    googleMaps: string;
  };
}

export const GBP_POST_TEMPLATES: GbpPostTemplate[] = [
  // ════════════════════════════════════════════════════
  // 🔴 PRIORITY TIER 1: Weakest keywords needing URGENT push
  //    These are published FIRST and MOST OFTEN until they hit Top 3
  // ════════════════════════════════════════════════════
  {
    keyword: 'ophtalmologue lyon',
    targetPage: 'https://centrerabelaislyon.fr/',
    textTemplate: '👁️ Centre Ophtalmologique Rabelais — votre ophtalmologue de référence au cœur de Lyon, à deux pas de Bellecour. Plateau technique de dernière génération : OCT Spectral-Domain, angiographie, laser Argon/YAG, injections IVT anti-VEGF. Prise en charge complète des maladies de la rétine et de la macula le même jour.',
    imagePrompt: 'Photorealistic exterior photo of a premium medical eye clinic in Lyon France, elegant building facade, warm golden lighting, professional and welcoming, no text',
    callToAction: 'Prendre rendez-vous',
  },
  {
    keyword: 'ophtalmologiste lyon',
    targetPage: 'https://centrerabelaislyon.fr/',
    textTemplate: '🏥 Vous cherchez un ophtalmologiste à Lyon ? Le Centre Rabelais vous accueille sans délai excessif pour un diagnostic complet. Spécialistes de la rétine médicale, de la DMLA et des pathologies maculaires. Secteur 2 conventionné.',
    imagePrompt: 'Professional female ophthalmologist in white coat with modern diagnostic equipment in premium Lyon clinic, warm lighting, photorealistic, no text',
    callToAction: 'Prendre rendez-vous',
  },
  {
    keyword: 'rdv ophtalmologue lyon',
    targetPage: 'https://centrerabelaislyon.fr/rdv',
    textTemplate: '📞 Besoin d\'un rendez-vous ophtalmologue à Lyon ? Le Centre Rabelais vous propose des créneaux rapides pour les urgences rétiniennes (DMLA humide, décollement, baisse de vision brutale). Appelez le 04 78 95 09 08, du lundi au vendredi.',
    imagePrompt: 'Modern medical reception desk in premium ophthalmology clinic, welcoming secretary, clean bright interior, photorealistic, no text',
    callToAction: 'Prendre rendez-vous',
  },
  {
    keyword: 'urgence ophtalmologique lyon',
    targetPage: 'https://centrerabelaislyon.fr/',
    textTemplate: '🚨 Urgence ophtalmologique à Lyon ? Baisse de vision brutale, éclairs lumineux, voile gris ? Le Centre Rabelais priorise les urgences rétiniennes avec diagnostic OCT + traitement le jour même. Ne tardez pas : chaque heure compte.',
    imagePrompt: 'Urgent medical ophthalmology scene, doctor examining patient eye with OCT device, fast professional care, photorealistic, no text',
    callToAction: 'Appeler maintenant',
  },
  {
    keyword: 'ophtalmologue villeurbanne',
    targetPage: 'https://centrerabelaislyon.fr/ophtalmologue-villeurbanne',
    textTemplate: '📍 Villeurbannais, votre spécialiste rétine est à 10 minutes ! Le Centre Ophtalmologique Rabelais (métro Bellecour) vous accueille pour le diagnostic et le traitement de la DMLA, de la rétinopathie diabétique et de toutes les pathologies maculaires.',
    imagePrompt: 'Beautiful cityscape of Villeurbanne near Lyon with modern buildings, warm golden hour, photorealistic, no text',
    callToAction: 'Nous trouver',
  },

  // ════════════════════════════════════════════════════
  // 🟡 PRIORITY TIER 2: Mid-range keywords to push from Top 4-10 → Top 3
  // ════════════════════════════════════════════════════
  {
    keyword: 'traitement dmla lyon',
    targetPage: 'https://centrerabelaislyon.fr/dmla-lyon',
    textTemplate: '🔬 DMLA : ne laissez pas votre vision se dégrader. Au Centre Rabelais, diagnostic OCT immédiat et traitement le même jour. DMLA humide : injections IVT anti-VEGF (Eylea®, Vabysmo®). DMLA sèche : photobiomodulation Valeda®, 1er traitement approuvé FDA.',
    imagePrompt: 'Hyper-realistic 3D medical illustration of a healthy human retina and macula, golden healing light, dark blue medical science aesthetic, premium quality, no text',
    callToAction: 'Consulter un spécialiste',
  },
  {
    keyword: 'injection intravitréenne lyon',
    targetPage: 'https://centrerabelaislyon.fr/injections-intravitreennes-lyon',
    textTemplate: '💉 Peur de l\'injection dans l\'œil ? Rassurez-vous : les IVT anti-VEGF au Centre Rabelais sont TOTALEMENT INDOLORES. Aiguilles ultra-fines 30G, salle stérile dédiée, protocole aseptique bétadine 5%. Prise en charge urgente à J+0.',
    imagePrompt: 'Reassuring ophthalmologist preparing intravitreal injection in sterile room, calm atmosphere, professional equipment, photorealistic, no text',
    callToAction: 'En savoir plus',
  },
  {
    keyword: 'rétinologue lyon',
    targetPage: 'https://centrerabelaislyon.fr/retinologue-lyon-6',
    textTemplate: '🏥 Dr QUARANTA, rétinologue exclusif au Centre Rabelais Lyon. Spécialiste de la rétine médicale : DMLA, rétinopathie diabétique, occlusions veineuses, membranes épirétiniennes. Diagnostic + traitement le même jour.',
    imagePrompt: 'Professional retina specialist doctor examining eye with advanced OCT imaging device, premium ophthalmology clinic, warm lighting, photorealistic, no text',
    callToAction: 'Prendre rendez-vous',
  },
  {
    keyword: 'oct macula lyon',
    targetPage: 'https://centrerabelaislyon.fr/oct-macula-lyon',
    textTemplate: '📸 OCT maculaire Spectral-Domain au Centre Rabelais : résolution 3-5 microns, sans dilatation, résultat immédiat. L\'examen clé pour diagnostiquer DMLA, œdème maculaire et glaucome. Interprétation par notre rétinologue le jour même.',
    imagePrompt: 'Hyper-realistic photo of modern OCT scanning device in ophthalmology clinic, patient being scanned, blue and gold professional atmosphere, photorealistic, no text',
    callToAction: 'En savoir plus',
  },
  {
    keyword: 'fond oeil lyon',
    targetPage: 'https://centrerabelaislyon.fr/oct-macula-lyon',
    textTemplate: '🔍 Fond d\'œil au Centre Rabelais Lyon : imagerie rétinienne haute résolution par OCT et angiographie. Dépistage précoce DMLA, rétinopathie diabétique, glaucome. Sans douleur, sans dilatation dans la majorité des cas. Résultat immédiat.',
    imagePrompt: 'Detailed medical retina imaging scan displayed on a monitor, modern ophthalmology clinic, photorealistic, no text',
    callToAction: 'Prendre rendez-vous',
  },
  {
    keyword: 'spécialiste rétine lyon',
    targetPage: 'https://centrerabelaislyon.fr/retine-medicale-lyon',
    textTemplate: '🧬 Centre Rabelais : le seul centre 100% dédié à la rétine médicale à Lyon. OCT, angiographie, laser, IVT, photobiomodulation — tout le spectre diagnostique et thérapeutique sur place. Pas de généralisme, que l\'excellence rétinienne.',
    imagePrompt: 'Aerial view of premium retina specialist medical center in Lyon, modern clean architecture, professional and elite, photorealistic, no text',
    callToAction: 'Consulter un spécialiste',
  },
  {
    keyword: 'rétinopathie diabétique lyon',
    targetPage: 'https://centrerabelaislyon.fr/pathologies-retiniennes',
    textTemplate: '⚠️ Diabétique ? Votre rétine est en danger. Le Centre Rabelais assure le dépistage et le suivi de la rétinopathie diabétique par OCT et angiographie. En cas de forme grave : laser rétinien et injections IVT anti-VEGF sans délai.',
    imagePrompt: 'Medical illustration of retinopathy examination with OCT device, diabetic patient care, professional clinic atmosphere, photorealistic, no text',
    callToAction: 'Dépister maintenant',
  },

  // ════════════════════════════════════════════════════
  // 🟢 PRIORITY TIER 3: Geo-local keywords for Google Maps dominance
  // ════════════════════════════════════════════════════
  {
    keyword: 'photobiomodulation lyon',
    targetPage: 'https://centrerabelaislyon.fr/photobiomodulation-lyon',
    textTemplate: '✨ Photobiomodulation Valeda® au Centre Rabelais : le 1er et seul centre à Lyon à proposer ce traitement FDA pour la DMLA sèche. 9 séances de 5 min, 0 douleur, résultats cliniques prouvés (études LIGHTSITE I/II/III).',
    imagePrompt: 'Advanced Valeda light therapy device treating patient eye with golden and red LED beams, modern ophthalmology clinic, dark navy and gold accents, photorealistic, no text',
    callToAction: 'Évaluer mon éligibilité',
  },
  {
    keyword: 'ophtalmologue lyon 6',
    targetPage: 'https://centrerabelaislyon.fr/ophtalmologue-lyon-6',
    textTemplate: '📍 Lyon 6ème — Brotteaux, Tête d\'Or : le Centre Rabelais est votre spécialiste rétine le plus proche. Accessible en 8 min depuis les Brotteaux (bus C1/C2). Diagnostic OCT + traitement le même jour.',
    imagePrompt: 'Beautiful aerial view of Lyon 6th arrondissement with Parc Tête d\'Or, warm sunset, premium quality, photorealistic, no text',
    callToAction: 'Nous trouver',
  },
  {
    keyword: 'ophtalmologue brotteaux',
    targetPage: 'https://centrerabelaislyon.fr/ophtalmologue-brotteaux',
    textTemplate: '🏙️ Depuis les Brotteaux, rejoignez le Centre Rabelais en 8 minutes (bus C1). Spécialiste exclusif de la rétine médicale à Lyon 2. Diagnostic complet + traitement DMLA/IVT le jour même.',
    imagePrompt: 'Elegant Brotteaux neighborhood in Lyon with train station and tree-lined avenues, warm golden hour, photorealistic cityscape, no text',
    callToAction: 'Prendre rendez-vous',
  },
  {
    keyword: 'ophtalmologue lyon 3',
    targetPage: 'https://centrerabelaislyon.fr/ophtalmologue-lyon-3',
    textTemplate: '📍 Lyon 3 / Part-Dieu : le Centre Rabelais est à 12 min en métro B. Spécialiste rétine : DMLA, rétinopathie diabétique, injections IVT. Diagnostic OCT immédiat sans dilatation.',
    imagePrompt: 'Modern Lyon Part-Dieu district with Tour de la Part-Dieu visible, urban warm lighting, photorealistic, no text',
    callToAction: 'Nous trouver',
  },
  {
    keyword: 'ophtalmologue lyon 7',
    targetPage: 'https://centrerabelaislyon.fr/ophtalmologue-lyon-7',
    textTemplate: '📍 Lyon 7ème / Jean Macé : le Centre Rabelais est votre centre rétine le plus proche (15 min en tramway T1). Expertise DMLA, IVT, laser rétinien. Consultations rapides et prise en charge complète.',
    imagePrompt: 'Lyon 7th arrondissement with Jean Macé area, modern urban setting, warm golden hour, photorealistic cityscape, no text',
    callToAction: 'Nous trouver',
  },
  {
    keyword: 'ophtalmologue lyon 8',
    targetPage: 'https://centrerabelaislyon.fr/ophtalmologue-lyon-8',
    textTemplate: '📍 Lyon 8 / Monplaisir : besoin d\'un spécialiste rétine ? Le Centre Rabelais (métro D puis A) vous attend pour un diagnostic OCT complet et un traitement adapté le même jour.',
    imagePrompt: 'Lyon 8th Monplaisir neighborhood, charming streets and local shops, warm urban atmosphere, photorealistic, no text',
    callToAction: 'Nous trouver',
  },
  {
    keyword: 'ophtalmologue bellecour',
    targetPage: 'https://centrerabelaislyon.fr/',
    textTemplate: '🌟 Place Bellecour → 2 minutes à pied : le Centre Ophtalmologique Rabelais. Consultations spécialisées rétine + macula, imagerie OCT haute résolution, traitements IVT et Photobiomodulation. L\'excellence au cœur de Lyon.',
    imagePrompt: 'Stunning photo of Place Bellecour Lyon at golden hour, elegant medical building nearby, warm atmospheric lighting, photorealistic, no text',
    callToAction: 'Prendre rendez-vous',
  },
  {
    keyword: 'dmla sèche traitement',
    targetPage: 'https://centrerabelaislyon.fr/photobiomodulation-lyon',
    textTemplate: '🌈 DMLA sèche : le Centre Rabelais est le seul à Lyon à proposer la Photobiomodulation Valeda® (FDA-approved). 9 séances de 5 min sur 3 semaines, 0 douleur, résultats prouvés. N\'attendez pas que la forme atrophique progresse.',
    imagePrompt: 'Advanced Valeda LED light therapy device with warm golden red and infrared beams, futuristic medical technology, dark blue and gold aesthetic, photorealistic, no text',
    callToAction: 'Évaluer mon éligibilité',
  },
  {
    keyword: 'ophtalmologue lyon 2',
    targetPage: 'https://centrerabelaislyon.fr/ophtalmologue-retine-lyon-2',
    textTemplate: '📍 Ophtalmologue Lyon 2 : le Centre Rabelais est le seul centre 100% dédié à la rétine de la Presqu\'île. Diagnostic OCT immédiat, IVT anti-VEGF, Photobiomodulation. À 2 min de Bellecour.',
    imagePrompt: 'Elegant Lyon Presqu\'île district with Saone river, medical building, warm golden hour, premium cityscape, photorealistic, no text',
    callToAction: 'Prendre rendez-vous',
  },

  // ════════════════════════════════════════════════════
  // 🔥 PRIORITY TIER 4: ALL SUBURBS + CLUSTER KEYWORDS
  //    Aggressive 5x/week — every arrondissement & big city
  // ════════════════════════════════════════════════════
  {
    keyword: 'ophtalmologue lyon 5',
    targetPage: 'https://centrerabelaislyon.fr/ophtalmologue-lyon-5',
    textTemplate: '📍 Lyon 5ème / Vieux Lyon : le Centre Rabelais (Place Bellecour) est votre spécialiste rétine le plus proche. Traversez la Saône en 5 min. DMLA, IVT, OCT, Photobiomodulation Valeda.',
    imagePrompt: 'Beautiful Vieux Lyon old town with Basilique Fourvière, warm golden light, photorealistic cityscape, no text',
    callToAction: 'Nous trouver',
  },
  {
    keyword: 'ophtalmologue lyon 9',
    targetPage: 'https://centrerabelaislyon.fr/ophtalmologue-lyon-9',
    textTemplate: '📍 Lyon 9 / Vaise : rejoignez le Centre Rabelais en 15 min (métro D). Spécialiste rétine : DMLA, rétinopathie diabétique, injections IVT. Diagnostic OCT le jour même.',
    imagePrompt: 'Lyon 9th Vaise district with Saone river and modern buildings, warm urban atmosphere, photorealistic, no text',
    callToAction: 'Nous trouver',
  },
  {
    keyword: 'ophtalmologue caluire',
    targetPage: 'https://centrerabelaislyon.fr/ophtalmologue-caluire-et-cuire',
    textTemplate: '📍 Caluire-et-Cuire : votre spécialiste rétine à 10 min en bus C1. Le Centre Rabelais (Bellecour) vous accueille pour DMLA, OCT, IVT anti-VEGF et Photobiomodulation.',
    imagePrompt: 'Caluire-et-Cuire residential area near Lyon, quiet green suburb, warm lighting, photorealistic, no text',
    callToAction: 'Nous trouver',
  },
  {
    keyword: 'ophtalmologue oullins',
    targetPage: 'https://centrerabelaislyon.fr/ophtalmologue-oullins',
    textTemplate: '📍 Oullins / Pierre-Bénite : le Centre Rabelais est accessible en 12 min (métro B). Seul centre 100% dédié rétine à Lyon. OCT, IVT, laser rétinien, Photobiomodulation.',
    imagePrompt: 'Oullins suburb of Lyon with Rhône river view, residential area, warm atmosphere, photorealistic, no text',
    callToAction: 'Nous trouver',
  },
  {
    keyword: 'ophtalmologue bron',
    targetPage: 'https://centrerabelaislyon.fr/ophtalmologue-bron',
    textTemplate: '📍 Bron / Saint-Priest : le Centre Rabelais (métro A + D) vous attend pour un diagnostic rétine complet. DMLA, rétinopathie, OCT Spectral-Domain, traitement le même jour.',
    imagePrompt: 'Bron city near Lyon with modern buildings and green spaces, warm urban atmosphere, photorealistic, no text',
    callToAction: 'Nous trouver',
  },
  {
    keyword: 'ophtalmologue part-dieu',
    targetPage: 'https://centrerabelaislyon.fr/ophtalmologue-part-dieu',
    textTemplate: '📍 Part-Dieu : le Centre Rabelais est à 12 min en métro B. Spécialiste rétine exclusif : DMLA, OCT maculaire, IVT anti-VEGF, Photobiomodulation Valeda. Prise en charge J+0.',
    imagePrompt: 'Lyon Part-Dieu tower and modern business district, warm golden hour, photorealistic cityscape, no text',
    callToAction: 'Nous trouver',
  },
  {
    keyword: 'ophtalmologue vénissieux',
    targetPage: 'https://centrerabelaislyon.fr/ophtalmologue-venissieux',
    textTemplate: '📍 Vénissieux / Minguettes : votre spécialiste rétine au Centre Rabelais (métro D). DMLA, rétinopathie diabétique, OCT haute résolution, injections IVT. Résultats immédiats.',
    imagePrompt: 'Vénissieux city near Lyon, residential area with modern amenities, warm atmospheric lighting, photorealistic, no text',
    callToAction: 'Nous trouver',
  },
  // ── CENTRE RÉTINE + DMLA geo clusters ──
  {
    keyword: 'centre rétine lyon',
    targetPage: 'https://centrerabelaislyon.fr/retine-medicale-lyon',
    textTemplate: "🏥 Centre Rabelais = le seul centre 100% rétine médicale à Lyon. Pas d'ophtalmologie générale. Uniquement l'expertise rétinienne : DMLA, OCT, IVT, laser, Photobiomodulation. Situé Place Bellecour, cœur de Lyon.",
    imagePrompt: 'Premium medical retina center interior with advanced OCT and laser equipment, elite professional atmosphere, photorealistic, no text',
    callToAction: 'Découvrir le centre',
  },
  {
    keyword: 'dmla lyon 6',
    targetPage: 'https://centrerabelaislyon.fr/dmla-lyon',
    textTemplate: '📍 DMLA à Lyon 6 ? Le Centre Rabelais (8 min des Brotteaux) est LE spécialiste. Diagnostic OCT immédiat + traitement le jour même : IVT anti-VEGF pour DMLA humide, Valeda® pour DMLA sèche.',
    imagePrompt: 'Medical OCT scan showing macular degeneration treatment, Lyon 6 background, professional medical aesthetic, photorealistic, no text',
    callToAction: 'Consulter un spécialiste',
  },
  {
    keyword: 'dmla villeurbanne',
    targetPage: 'https://centrerabelaislyon.fr/dmla-traitement-villeurbanne',
    textTemplate: '📍 Villeurbannais atteint de DMLA ? Le Centre Rabelais est à 10 min. Seul centre lyonnais proposant la Photobiomodulation Valeda® (DMLA sèche) + IVT anti-VEGF dernière génération (DMLA humide). Diagnostic OCT J+0.',
    imagePrompt: 'Villeurbanne cityscape with medical clinic direction arrows, warm golden hour, photorealistic, no text',
    callToAction: 'Prendre rendez-vous',
  },
  {
    keyword: 'rétinologue villeurbanne',
    targetPage: 'https://centrerabelaislyon.fr/retinologue-lyon-6',
    textTemplate: '📍 Villeurbanne : votre rétinologue exclusif est au Centre Rabelais (Place Bellecour, 10 min en métro A). Dr QUARANTA, spécialiste de la rétine médicale depuis 20 ans.',
    imagePrompt: 'Professional retina specialist in premium clinic with OCT device, Villeurbanne to Lyon direction, photorealistic, no text',
    callToAction: 'Prendre rendez-vous',
  },
  {
    keyword: 'ophtalmologue villeurbanne',
    targetPage: 'https://centrerabelaislyon.fr/ophtalmologue-villeurbanne',
    textTemplate: "📍 Villeurbanne → Centre Rabelais en 10 min (métro A Bellecour). Le centre de référence pour la rétine médicale : DMLA, rétinopathie diabétique, OCT, IVT, Photobiomodulation. Pas d'attente excessive.",
    imagePrompt: 'Villeurbanne modern cityscape with metro direction to Lyon center, warm golden hour, photorealistic, no text',
    callToAction: 'Nous trouver',
  },
];

// Competitor data for reports
export const COMPETITORS = [
  { name: 'Vision Future Lyon', url: 'visionfuture.fr', threat: 'high' as const, reviews: 346, rating: 4.7 },
  { name: 'Centre Ophtalmologique Kléber', url: 'centre-kleber.fr', threat: 'high' as const, reviews: 2900, rating: 4.7 },
  { name: 'Dr David Seifeddine', url: 'cliniquedelavuelyon.fr', threat: 'medium' as const, reviews: 843, rating: 4.7 },
  { name: 'CHU Edouard Herriot', url: 'chu-lyon.fr', threat: 'low' as const, reviews: 1200, rating: 3.9 },
  { name: 'Point Vision Lyon', url: 'pointvision.com', threat: 'medium' as const, reviews: 580, rating: 4.3 },
];
